### ISSUE TITLE
Build releases with tinygo for more reasonable size

### ISSUE THREAD

**Issue by coolaj86** [itchyny/base58-go#5]
Megabytes just seem a little big for a tool that manipulates strings to convert between a base number systems. Yeah, there's infinite space and infinite bandwidth these days but... still, just _feels_ wrong. Y'know? \
(and looks suspicious to the non-webdev, sysadmin types)

Anyway, if you compile with `tinygo`, the file size goes down, almost to a reasonable level.

- https://tinygo.org/
- https://webinstall.dev/tinygo/ (Installer + Cheat Sheet)

## TinyGo Sizes

Note: `-tags appengine` is used to prevent the unnecessary use of syscalls, which otherwise causes `tinygo` to fail.

```sh
tinygo build -o ./base58 -tags appengine ./cmd/base58/main.go
gzip --keep ./base58
tar cvzf base58.tar.gz ./base58
xz --keep ./base58
zip 'base58' ./base58
ls -lAhF ./base58*
```

```text
.rwxr-xr-x aj staff 498 KB Fri May  3 21:43:42 2024 ./base58*
.rwxr-xr-x aj staff 155 KB Fri May  3 21:43:42 2024 ./base58.gz*
.rw-r--r-- aj wheel 155 KB Fri May  3 21:43:42 2024 ./base58.tar.gz
.rwxr-xr-x aj staff 115 KB Fri May  3 21:43:42 2024 ./base58.xz*
.rw-r--r-- aj wheel 156 KB Fri May  3 21:43:42 2024 ./base58.zip
```

## Using `flag`

Unsurprisingly, the custom flag package is the majority of the weight. Replacing that with the standard library's `flag` cuts the size by nearly half again:

```text
.rwxr-xr-x aj staff 293 KB Fri May  3 21:51:11 2024 ./base58*
.rwxr-xr-x aj staff 103 KB Fri May  3 21:51:11 2024 ./base58.gz*
.rw-r--r-- aj wheel 103 KB Fri May  3 21:51:11 2024 ./base58.tar.gz
.rwxr-xr-x aj staff  78 KB Fri May  3 21:51:11 2024 ./base58.xz*
.rw-r--r-- aj wheel 103 KB Fri May  3 21:51:11 2024 ./base58.zip
```

That's just the same as about any other unix utility - twice the size of `cp` and the same size as `dash` on macOS.

## Current Go Sizes

Go's runtime is really huge because of the advanced 0-pause garbage collector that ships even when a simple garbage collector will do. Reflection can also bloat the size.

```sh
go build -tags appengine -ldflags '-s -w' -o ./base58 ./cmd/base58/
gzip --keep ./base58
tar cvzf base58.tar.gz ./base58
xz --keep ./base58
zip 'base58' ./base58
ls -lAhF ./base58*
```

```text
.rwxr-xr-x aj staff 1.7 MB Fri May  3 21:40:40 2024 ./base58*
.rwxr-xr-x aj staff 716 KB Fri May  3 21:40:40 2024 ./base58.gz*
.rw-r--r-- aj wheel 716 KB Fri May  3 21:42:37 2024 ./base58.tar.gz
.rwxr-xr-x aj staff 547 KB Fri May  3 21:40:40 2024 ./base58.xz*
.rw-r--r-- aj wheel 717 KB Fri May  3 21:40:58 2024 ./base58.zip
```

**Comment by itchyny** [comment]
Thanks for well described proposal.

The original intention of this package is to use for webdev in the company I used to belong to. One of the services uses base58 encoding of IDs for URL and created for my internal use in a Go server. I also created a cli, for getting the DB id from access log. It was actually useful indeed, but was not the main reason.
Also, I don't like to use non-standard compilers, because I don't want to be bothered by the differences (does it archived encoding/json compatibility?). I don't even want to learn appengine tag is good for smaller executables. I also want to use the official compiler in my projects, for newly added syntax like range over int. The tinygo solution might solve a kind of issues such as porting a command of thousands or millions of lines to a device with limited space. But base58-go is a tiny project, and it's better to find a better solution.
Although Go is the most familiar language for me, I strongly recommend to use Rust for your motivation. I learned Rust for a couple of years, and if I still worked for the company, I would have created base58-rs with a command line tool. I think Rust is the best language for small (features and executable size) command tools. Luckily you don't have to port yourself, [there already is a maintained tool](https://github.com/Nullus157/bs58-rs/tree/main/cli).

Anyway, I have no much motivation on base58 encoding anymore since I changed my job. Sorry for that.

**Comment by coolaj86** [comment]
The problem with Rust is the cross-compile story - which shows because hardly any Rust projects have official releases (ex: <https://github.com/Nullus157/bs58-rs/releases>). Every now and then I search to see if Rust has gotten any closer to something like GoReleaser, but so far all my cross-compile attempts have floundered.

If I were going to write something like this myself, I'd use Zig.

If I were going to publish this myself, I'd be torn between a quick Zig + Zig-Releaser port, or just forking this, swapping the `flag` package and give it parity with the `base64` command.

But... what I actually did for my use case was this:
```sh
aliasman alias rnd58='xxd -c 0 -l 256 -p /dev/urandom | xxd -r -ps | base64 -b 0 | tr -d /+_-= | tr -d 0IOl | cut -c 1-80'
alias rnd58='xxd -c 0 -l 256 -p /dev/urandom | xxd -r -ps | base64 -b 0 | tr -d /+_-= | tr -d 0IOl | cut -c 1-80'

# 128 bits of entropy
rnd58 | cut -c 1-22

# 256 bits of entropy
rnd58 | cut -c 1-44
```

(I wanted a `base58` command to replace the `base64` command)

Go is my favorite language. I love it. I just wish it were easier to make CLI tools that don't bloat to 10s or 100s of megabytes.

I only learned about `appengine` because I was reading the source of the flags package trying to determine why it was pulling in `x/sys` and why it was making syscalls. That's not a conventional tag.

I totally get wanting to use the official compiler. TinyGo doesn't have parity for `x/sys`, nor things that rely on certain types of reflection.

Again, it's not about fitting it on a tiny device, it's just that I come from the late 90s era of Linuxing and I personally have run up against people who see large files as a security threat and do not want them in their processes - and so I try to keep any sort of process I create bounded to what the larger sysadmin community will accept without too much stink-eyeing.

Have a good one! Adios.

**Comment by itchyny** [comment]
I removed the dependency on go-flags in 3c65b182f22bbe71f4bfb56bdf8f9be84af0bbfd, inspired by this issue.
